apiVersion: apps/v1
kind: Deployment
metadata:
  name: moto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moto
  template:
    metadata:
      labels:
        app: moto
    spec:
      containers:
      - name: moto
        image: ridhabucket/moto:latest
        ports:
        - containerPort: 8080
