apiVersion: apps/v1
kind: Deployment
metadata:
  name: moto-deployment
  labels:
    app: moto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moto
  template:
    metadata:
      labels:
        app: moto
    spec:
      containers:
        - name: moto-container
          image: ridhabucket/moto:latest
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: s3-service
spec:
  selector:
    app: moto
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: bestmoto
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s3-service
                port:
                  number: 9000
  tls:
    - hosts:
        - bestmoto
      secretName: moto-cdpi-atelier-ovh-tls
