apiVersion: v1
kind: Service
metadata:
  name: s3-service
spec:
  selector:
    app: moto
  type: LoadBalancer  # Or NodePort, depending on your setup
  ports:
    - protocol: TCP
      port: 9000        # Port accessible externally
      targetPort: 9000  # Port on which your pod is listening
