apiVersion: v1
kind: Service
metadata:
  name: moto-service
spec:
  selector:
    app: moto
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000        # Port accessible externally
      targetPort: 9000  # Port on which your pods are listening

