apiVersion: v1
kind: Service
metadata:
  name: moto-service
spec:
  selector:
    app: moto
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000        # Port exposé à l'extérieur
      targetPort: 9000  # Port sur lequel les pods écoutent
