apiVersion: v1
kind: Service
metadata:
  name: moto-service
spec:
  selector:
    app: moto
  ports:
  - protocol: TCP
    port: 80  # Port exposé
    targetPort: 8080  # Port du container
  type: LoadBalancer  # Utilise LoadBalancer pour exposer publiquement l'application
