name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image and run tests
        run: docker build -t your-dockerhub-username/plateforme-mys3 ./plateforme-mys3

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag your-dockerhub-username/plateforme-mys3:latest your-dockerhub-username/plateforme-mys3:${{ github.sha }}
          docker push your-dockerhub-username/plateforme-mys3:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0'  # Remplace par la version kubectl de ton cluster

      - name: Configure kubectl to access the cluster
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          
      - name: Deploy to Kubernetes
        run: kubectl apply -f ./deployment.yaml
