name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install dependencies
        working-directory: ./plateforme-mys3
        run: go mod download

      - name: Run tests
        working-directory: ./plateforme-mys3
        run: go test ./cmd/... -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        working-directory: ./plateforme-mys3
        run: |
          docker build -t ridhabucket/moto:${{ github.sha }} .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag ridhabucket/moto:${{ github.sha }} ridhabucket/moto:latest
          docker push ridhabucket/moto:${{ github.sha }}
          docker push ridhabucket/moto:latest
