name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build the application
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .
          docker tag your-image-name your-docker-repo/your-image-name:latest
          docker push your-docker-repo/your-image-name:latest

      - name: Notify Google Chat
        uses: 360kelvin/chat-notifier@v2.2.0
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          message: 'Build and deployment succeeded for ${{ github.sha }}'
