name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ridhabucket/moto:${{ github.sha }} .
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin --quiet
          docker tag ridhabucket/moto:${{ github.sha }} ridhabucket/moto:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ridhabucket/moto:${{ github.sha }}
          docker push ridhabucket/moto:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: ${{ secrets.KUBECTL_VERSION }}

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/moto moto=ridhabucket/moto:latest
          kubectl rollout status deployment/moto
